services:
  api:
    build: ./services/api
    ports: ["8000:8000"]
    environment:
      - DATA_DIR=/app/data
      - ORCHESTRATOR_URL=http://orchestrator:8010
    volumes:
      - ./data:/app/data
    depends_on:
      - orchestrator

  orchestrator:
    build: ./services/orchestrator
    ports: ["8010:8010"]
    environment:
      - DATA_DIR=/app/data
      - DOC_ANALYZER_URL=http://doc-analyzer:8111
      - GAP_ANALYSIS_URL=http://gap-analysis:8121
      - INITIATIVE_URL=http://initiative-gen:8131
      - PRIORITIZATION_URL=http://prioritization:8141
      - ROADMAP_URL=http://roadmap-planner:8151
      - REPORT_URL=http://report-generator:8161
    volumes:
      - ./data:/app/data
    depends_on:
      - doc-analyzer
      - gap-analysis
      - initiative-gen
      - prioritization
      - roadmap-planner
      - report-generator

  doc-analyzer:
    build: ./services/agents/documentation_analyzer
    ports: ["8111:8111"]

  gap-analysis:
    build: ./services/agents/gap_analysis
    ports: ["8121:8121"]

  initiative-gen:
    build: ./services/agents/initiative_generation
    ports: ["8131:8131"]

  prioritization:
    build: ./services/agents/prioritization
    ports: ["8141:8141"]

  roadmap-planner:
    build: ./services/agents/roadmap_planner
    ports: ["8151:8151"]

  report-generator:
    build: ./services/agents/report_generator
    ports: ["8161:8161"]

  # In production, you’ll replace local persistence with Cosmos DB and add
  # Azure Service Bus. For local MVP we just write to ./data.
