name: build-and-deploy

on:
  workflow_dispatch:
  # Disabled automatic triggers until secrets are configured
  # push:
  #   branches: [ main ]

# Set default permissions to read-only for security
permissions:
  contents: read
  packages: write

# Prevent multiple runs for the same ref
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GHCR_ENABLED: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Set lowercase repository owner
        run: echo "REPO_OWNER_LOWER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      # OAuth scope fix verified - can now modify workflows!
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Web image
        uses: docker/build-push-action@v5
        with:
          context: ./web
          push: true
          tags: |
            ghcr.io/${{ env.REPO_OWNER_LOWER }}/aecma-web:${{ github.sha }}
            ghcr.io/${{ env.REPO_OWNER_LOWER }}/aecma-web:latest
          build-args: |
            GITHUB_SHA=${{ github.sha }}
            BUILD_SHA=${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # Fallback deployment when Azure credentials are not available
  deploy-fallback:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ secrets.AZURE_CREDENTIALS == '' }}
    steps:
      - name: Set lowercase repository owner
        run: echo "REPO_OWNER_LOWER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
        
      - name: Deployment Status - Azure Credentials Missing
        run: |
          echo "🔧 DEPLOYMENT STATUS: PARTIAL SUCCESS"
          echo ""
          echo "✅ Code fixes successfully built and pushed to registry"
          echo "✅ Docker image available at: ghcr.io/${{ env.REPO_OWNER_LOWER }}/aecma-web:${{ github.sha }}"
          echo ""
          echo "❌ Production deployment skipped - Azure credentials not configured"
          echo ""
          echo "📋 To complete production deployment:"
          echo "1. Configure Azure secrets in repository settings"
          echo "2. Run: gh workflow run .github/workflows/release.yml"
          echo ""
          echo "🏷️  Image Tag: ${{ github.sha }}"
          echo "📦 Registry: GitHub Container Registry (GHCR)"

  # Verify deployment when Azure credentials are available  
  verify-deployment:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ secrets.AZURE_CREDENTIALS != '' }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Trigger Production Deployment
        run: |
          echo "🚀 Triggering production deployment via release workflow..."
          gh workflow run .github/workflows/release.yml --ref ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Wait for deployment
        run: |
          echo "⏳ Waiting for deployment to complete..."
          sleep 30
      
      - name: Verify production deployment
        run: |
          echo "🔍 Verifying production deployment..."
          
          # Try to check production version
          if curl -s --max-time 10 https://aecma-prod.azurewebsites.net/api/version | grep -q "${{ github.sha }}"; then
            echo "✅ Production deployment successful - version matches"
          else
            echo "⚠️  Production version check failed or still updating"
            echo "🔄 Deployment may still be in progress"
          fi